#!/bin/bash

if [ $(id -u) -ne 0 ]; then
	echo "You need to be root or sudo to use this script!"
	exit 0
fi;

if [ -f ./old_crontab ]; then
	if [ -n "$(diff /etc/crontab ./old_crontab)" ]; then
		echo "Hey, crontab has been edited!" | mail -s "Crontab edited !" root
	fi;
fi;

cp /etc/crontab ./old_crontab
